---
title: "Coronavirus Data Visualizer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(httr)
library(jsonlite)
library(dplyr)
library(plotly)
library(prophet)
library(dygraphs)
library(shinyBS)
```

Column {.sidebar}
-----------------------------------------------------------------------

### 

```{r}
       country_url <- "https://api.covid19api.com/countries"
       countries <- GET(country_url) %>% content("text") %>% fromJSON() %>% as.data.frame()
       selectInput(inputId = "country", label = "Select a Country to Plot", choices = sort(countries$Country))
```






Row
---------

### Daily Cases and Recovereds

```{r}

 renderPlotly({
  
  country_url <- "https://api.covid19api.com/countries"
  countries <- GET(country_url) %>% content("text") %>% fromJSON() %>% as.data.frame()
        
  country_slug <- countries[countries$Country == input$country,]$Slug
        
        
  url <- paste0("https://api.covid19api.com/total/country/", country_slug)
  info_df <- GET(url) %>% content("text") %>% fromJSON() %>% as.data.frame()
  info_df$Daily_Confirmed <- NA
  info_df[1,]$Daily_Confirmed <- 0
  info_df$Daily_Deaths <- NA
  info_df[1,]$Daily_Deaths <- 0
  info_df$Daily_Recovered <- NA
  info_df[1,]$Daily_Recovered <- 0
  
  daily_cases <- c()
  daily_deaths <- c()
  daily_recovered <- c()
  for (i in seq(2, nrow(info_df))) {
    daily_cases <- c(daily_cases, info_df[i,]$Confirmed - info_df[i-1,]$Confirmed)
    daily_deaths <- c(daily_deaths, info_df[i,]$Deaths - info_df[i-1,]$Deaths)
    daily_recovered <- c(daily_recovered, info_df[i,]$Recovered - info_df[i-1,]$Recovered)
  }
  
  info_df[2:nrow(info_df),]$Daily_Confirmed <- daily_cases
  info_df[2:nrow(info_df),]$Daily_Deaths <- daily_deaths
  info_df[2:nrow(info_df),]$Daily_Recovered <- daily_recovered
        
 
        fig <- plot_ly(info_df, x = ~ as.Date(Date), name = "Date")
        
        fig <- fig %>% 
            add_lines(y = ~ Daily_Confirmed, name = "Confirmed Cases") %>% 
            add_lines(y = ~ Daily_Recovered, name = "Recovered")
           
        
        fig <- fig %>% layout(
            title = paste("Daily Cases and Recovereds in", input$country),
            xaxis = list(
                title = "Date",
                rangeselector = list(
                    buttons = list(
                        list (
                            count = 3,
                            label = "3 months",
                            step = "month",
                            stepmode = "backward"
                        ),
                        list (
                            count = 6,
                            label = "6 months",
                            step = "month",
                            stepmode = "backward"
                        ),
                        list (
                            count = 1,
                            label = "1 year",
                            step = "year",
                            stepmode = "backward"
                        ),
                        list (
                            count = 1,
                            label = "ytd",
                            step = "year",
                            stepmode = "todate"
                        ),
                        list(step = "all"))),
                rangeslider = list(type = "date")),
            yaxis = list(title = ""))
        
        fig
         

})
  



```

Row 
----------
### Daily Deaths

```{r}

renderPlotly({
  
   country_url <- "https://api.covid19api.com/countries"
  countries <- GET(country_url) %>% content("text") %>% fromJSON() %>% as.data.frame()
  
  country_slug <- countries[countries$Country == input$country,]$Slug
  
  url <- paste0("https://api.covid19api.com/total/country/", country_slug)
  info_df <- GET(url) %>% content("text") %>% fromJSON() %>% as.data.frame()
  info_df$Daily_Confirmed <- NA
  info_df[1,]$Daily_Confirmed <- 0
  info_df$Daily_Deaths <- NA
  info_df[1,]$Daily_Deaths <- 0
  info_df$Daily_Recovered <- NA
  info_df[1,]$Daily_Recovered <- 0
  
  daily_cases <- c()
  daily_deaths <- c()
  daily_recovered <- c()
  for (i in seq(2, nrow(info_df))) {
    daily_cases <- c(daily_cases, info_df[i,]$Confirmed - info_df[i-1,]$Confirmed)
    daily_deaths <- c(daily_deaths, info_df[i,]$Deaths - info_df[i-1,]$Deaths)
    daily_recovered <- c(daily_recovered, info_df[i,]$Recovered - info_df[i-1,]$Recovered)
  }
  
  info_df[2:nrow(info_df),]$Daily_Confirmed <- daily_cases
  info_df[2:nrow(info_df),]$Daily_Deaths <- daily_deaths
  info_df[2:nrow(info_df),]$Daily_Recovered <- daily_recovered
  
  
  fig <- plot_ly(info_df, x = ~ as.Date(Date), name = "")
  
  fig <- fig %>% 
    add_lines(y = ~ Daily_Deaths, name = "")
  
  
  fig <- fig %>% layout(
    title = paste("Daily Deaths in", input$country),
    xaxis = list(
      title = "Date",
      rangeselector = list(
        buttons = list(
          list (
            count = 3,
            label = "3 months",
            step = "month",
            stepmode = "backward"
          ),
          list (
            count = 6,
            label = "6 months",
            step = "month",
            stepmode = "backward"
          ),
          list (
            count = 1,
            label = "1 year",
            step = "year",
            stepmode = "backward"
          ),
          list (
            count = 1,
            label = "ytd",
            step = "year",
            stepmode = "todate"
          ),
          list(step = "all"))),
      rangeslider = list(type = "date")),
    yaxis = list(title = ""))
  
  fig
        
  
})


```


World Map
==========================

Row {data-height = 650}
--------------------------

### World Map

```{r}

renderLeaflet({
  
countries_shp <- geojson_read("countries.geo.json", what = "sp")
countries_shp@data[countries_shp@data$name == "Russia",]$name <- "Russian Federation"
countries_shp@data[countries_shp@data$name == "Republic of Serbia",]$name <- "Serbia"



world_url <- "https://api.covid19api.com/summary"
world_list <- GET(world_url) %>% content("text") %>% fromJSON() 
world_df <- world_list[4]

summary_df <- world_df[["Countries"]]
summary_df <- summary_df %>% select(c("Country", "TotalConfirmed", "TotalDeaths"))

## Correcting names of some of the countries

summary_df[summary_df$Country == "Venezuela (Bolivarian Republic)",]$Country <- "Venezuela"
summary_df[summary_df$Country == "Congo (Kinshasa)",]$Country <- "Democratic Republic of the Congo"
summary_df[summary_df$Country == "Congo (Brazzaville)",]$Country <- "Republic of the Congo"
summary_df[summary_df$Country == "Tanzania, United Republic of",]$Country <- "United Republic of Tanzania"
summary_df[summary_df$Country == "Côte d'Ivoire",]$Country <- "Ivory Coast"
summary_df[summary_df$Country == "Syrian Arab Republic (Syria)",]$Country <- "Syria"
summary_df[summary_df$Country == "Iran, Islamic Republic of",]$Country <- "Iran"
summary_df[summary_df$Country == "Viet Nam",]$Country <- "Vietnam"
summary_df[summary_df$Country == "Macedonia, Republic of",]$Country <- "Macedonia"
summary_df[summary_df$Country == "Korea (South)",]$Country <- "South Korea"
summary_df[summary_df$Country == "Republic of Kosovo",]$Country <- "Kosovo"
summary_df[summary_df$Country == "Guinea-Bissau",]$Country <- "Guinea Bissau"
summary_df[summary_df$Country == "Lao PDR",]$Country <- "Laos"
summary_df[summary_df$Country == "Taiwan, Republic of China",]$Country <- "Taiwan"
summary_df[summary_df$Country == "Guyana",]$Country <- "French Guiana"


data_Map <- countries_shp[countries_shp$name %in% summary_df$Country,]

data_Map@data$case_numbers <- summary_df$TotalConfirmed[match(data_Map@data$name, summary_df$Country)]
data_Map@data$death_numbers <- summary_df$TotalDeaths[match(data_Map@data$name, summary_df$Country)]



mytext <- paste(
  "Country:", data_Map@data$name, "<br>",
  "Total Confirmed Cases:", data_Map@data$case_numbers,"<br>",
  "Total Deaths:", data_Map@data$death_numbers
) %>% 
   lapply(htmltools::HTML)

pal <- colorBin("YlOrRd", domain = data_Map@data$numbers, bins = c(0,10000,50000,100000,500000,1000000, 50000000))

leaflet(data_Map) %>%
  addTiles(options = tileOptions(minZoom = 1.5, maxZoom = 18)) %>% 
  addPolygons(fillColor = ~pal(data_Map@data$case_numbers),
              color = "white",
              stroke = T,
              opacity = 1,
              fillOpacity = 0.9, 
              weight = 0.3,
              dashArray = 1,
              label = mytext,
              labelOptions = labelOptions(textsize = 15),
              highlightOptions = highlightOptions(weight = 3, color = "grey", dashArray = "", fillOpacity = 0.7, bringToFront = TRUE)) %>%
  addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
  position = "bottomright") 
  
})
```




Make Predictions
================================

Column {.sidebar}
---------------------------------------

### 

```{r}
      country_url <- "https://api.covid19api.com/countries"
      countries <- GET(country_url) %>% content("text") %>% fromJSON() %>% as.data.frame()
        selectInput(inputId = "country_p", label = "Select a Country", choices = sort(countries$Country))
        selectInput(inputId = "category", label = "Select a Category", choices = c("Confirmed", "Deaths"))
        selectInput(inputId = "period", label = "Select a Period", choices = c("1 Month","3 Months","5 Months"))
        selectInput(inputId = "changepoint", label = "Changepoint Prior Scale", choices = c(0.001, 0.01, 0.1,0.05, 0.5), selected = 0.05)
        selectInput(inputId = "seasonality", label = "Seasonality Prior Scale", choices = c(0.1, 0.5,1,5,10), selected = 10)
        selectInput(inputId = "holidays", label = "Holidays Prior Scale", choices = c(0.1, 0.5,1,5,10), selected = 10)
        selectInput(inputId = "seasonality_mode", label = "Seasonality Mode", choices = c("Additive", "Multiplicative"), selected = "Additive")
      
        bsTooltip(id = "changepoint", trigger = "hover", title = "Changepoint Prior Scale determines the flexibility of the trend, and in particular how much the trend changes at the trend changepoints.If it is too small, the trend will be underfit and variance that should have been modeled with trend changes will instead end up being handled with the noise term. If it is too large, the trend will overfit and in the most extreme case you can end up with the trend capturing yearly seasonality.(Default = 0.05)")
        bsTooltip(id = "seasonality", trigger = "hover", title = "Seasonality Prior Scale controls the flexibility of the seasonality. Similarly, a large value allows the seasonality to fit large fluctuations, a small value shrinks the magnitude of the seasonality. (Default = 10)")
        bsTooltip(id = "holidays", trigger = "hover", title = "Holidays Prior Scale controls flexibility to fit holiday effects. Similar to seasonality_prior_scale, it defaults to 10.0 which applies basically no regularization, since we usually have multiple observations of holidays and can do a good job of estimating their effects. This could also be tuned on a range of [0.01, 10] as with seasonality_prior_scale.")
        bsTooltip(id = "seasonality_mode", trigger = "hover", title =  "Options are ['additive', 'multiplicative']. Default is 'additive', but many business time series will have multiplicative seasonality. This is best identified just from looking at the time series and seeing if the magnitude of seasonal fluctuations grows with the magnitude of the time series (see the documentation here on multiplicative seasonality), but when that isn’t possible, it could be tuned.")
    
```

Row 
---------------------------

### Prediction Chart

```{r}


  renderDygraph({
    
country_url <- "https://api.covid19api.com/countries"
countries <- GET(country_url) %>% content("text") %>% fromJSON() %>% as.data.frame()
       
country_slug <- countries[countries$Country == input$country_p,]$Slug

url <- paste0("https://api.covid19api.com/total/country/", country_slug)
info_df <- GET(url) %>% content("text") %>% fromJSON() %>% as.data.frame()

predict_data <- info_df[,c("Date", input$category)]
  
colnames(predict_data) <- c("ds", "y")
  
predict_data$ds <- as.Date(predict_data$ds)
  
model <- prophet(predict_data, changepoint.prior.scale = as.numeric(input$changepoint), seasonality.prior.scale = as.numeric(input$seasonality), holidays.prior.scale = as.numeric(input$holidays), seasonality.mode = tolower(input$seasonality_mode))


time_period <- case_when(input$period == "1 Month" ~ 30, input$period == "3 Months" ~ 90, input$period == "5 Months" ~ 150)
  
future_predicts <- make_future_dataframe(model, periods = time_period)

forecast <- predict(model, future_predicts)

    
dyplot.prophet(model, forecast)%>%
      dyOptions(maxNumberWidth = 20)
    
  })



```






